#!/bin/bash
# WordPress Docker Environment - Quick Commands Reference

echo "=========================================="
echo "WordPress Docker - Quick Commands"
echo "=========================================="
echo ""
echo "📦 Container Management"
echo "  Start:     docker-compose up -d"
echo "  Stop:      docker-compose stop"
echo "  Restart:   docker-compose restart"
echo "  Status:    docker-compose ps"
echo "  Logs:      docker-compose logs -f"
echo ""
echo "🌐 Access URLs"
echo "  WordPress:   http://localhost:8080"
echo "  phpMyAdmin:  http://localhost:8081"
echo ""
echo "🗄️  Database"
echo "  Host:        db (from containers) or localhost:3306 (from host)"
echo "  Database:    wordpress"
echo "  User:        wpuser"
echo "  Password:    wppassword"
echo "  Root Pass:   rootpassword"
echo ""
echo "🔧 Maintenance"
echo "  Rebuild:     docker-compose build --no-cache"
echo "  Clean up:    docker-compose down"
echo "  Full reset:  docker-compose down -v  (⚠️  deletes database!)"
echo ""
echo "📝 Database Commands"
echo "  Backup:      docker exec wp-mariadb mysqldump -uwpuser -pwppassword wordpress > backup.sql"
echo "  Restore:     docker exec -i wp-mariadb mysql -uwpuser -pwppassword wordpress < backup.sql"
echo "  Shell:       docker exec -it wp-mariadb mysql -uwpuser -pwppassword"
echo ""
echo "🐛 Debugging"
echo "  Container logs:      docker logs wp-app -f"
echo "  Database logs:       docker logs wp-mariadb -f"
echo "  Shell into WP:       docker exec -it wp-app bash"
echo "  Shell into DB:       docker exec -it wp-mariadb bash"
echo ""
